/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semestral.view.treinos;

import semestral.pojo.treinos.treino_aluno_POJO;

/**
 *
 * @author guilh
 */
public class tela_cadastrar_treino_aluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastrar_treino_aluno
     */
    public tela_cadastrar_treino_aluno() {
        initComponents();
    }
  public String[] monta_cadastro(treino_aluno_POJO treino_aluno){
        String[] dados = {"id_treino","id_aluno","data_inicio","data_termino",treino_aluno.getId_treino()+"",treino_aluno.getData_inicio(),treino_aluno.getEstado()+"",treino_aluno.getData_termino()};    
        return dados;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
