/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semestral.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import semestral.view.aluno.tela_cadastro_aluno;
import semestral.view.aluno.tela_aluno;
import semestral.view.aluno.tela_aluno_menu;
import semestral.view.treinos.tela_treino;


/**
 *
 * @author guilh
 */
public class Tela_principal extends javax.swing.JFrame {
navegacao navega = new navegacao();
    /**
     * Creates new form tela_inicial
     */
    public Tela_principal() {
        initComponents();
        ajustar_tela();
        tela_home tela_home = new tela_home(Area_trabalho.getSize());
        tela_home_menu tela_home_menu = new tela_home_menu(Area_menu.getSize(),Area_menu,Area_trabalho, tela_home);
        tela_treino tela_fechar = new tela_treino(Area_trabalho.getSize());
        navega.navegar(Area_trabalho,Area_menu, tela_home, tela_home_menu, tela_fechar, tela_fechar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Area_trabalho = new javax.swing.JDesktopPane();
        Area_menu = new javax.swing.JDesktopPane();
        L_fechar = new javax.swing.JLabel();
        L_minimizar = new javax.swing.JLabel();
        L_maximizar = new javax.swing.JLabel();
        L_imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Area_trabalho.setPreferredSize(new java.awt.Dimension(1230, 750));
        Area_trabalho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Area_trabalhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Area_trabalhoLayout = new javax.swing.GroupLayout(Area_trabalho);
        Area_trabalho.setLayout(Area_trabalhoLayout);
        Area_trabalhoLayout.setHorizontalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        Area_trabalhoLayout.setVerticalGroup(
            Area_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );

        getContentPane().add(Area_trabalho);
        Area_trabalho.setBounds(160, 28, 1206, 742);
        Area_trabalho.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout Area_menuLayout = new javax.swing.GroupLayout(Area_menu);
        Area_menu.setLayout(Area_menuLayout);
        Area_menuLayout.setHorizontalGroup(
            Area_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        Area_menuLayout.setVerticalGroup(
            Area_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );

        getContentPane().add(Area_menu);
        Area_menu.setBounds(0, 28, 160, 742);

        L_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_fecharMouseClicked(evt);
            }
        });
        getContentPane().add(L_fechar);
        L_fechar.setBounds(1330, 0, 40, 40);

        L_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(L_minimizar);
        L_minimizar.setBounds(1250, 0, 30, 40);

        L_maximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_maximizarMouseClicked(evt);
            }
        });
        getContentPane().add(L_maximizar);
        L_maximizar.setBounds(1300, 0, 30, 40);

        L_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semestral/imagem/topo/Barra.png"))); // NOI18N
        L_imagem.setPreferredSize(new java.awt.Dimension(1366, 35));
        getContentPane().add(L_imagem);
        L_imagem.setBounds(0, 0, 1366, 28);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_fecharMouseClicked
        System.out.println("cliquei em fechar");
        this.dispose();

    }//GEN-LAST:event_L_fecharMouseClicked

    private void L_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_minimizarMouseClicked
        System.out.println("cliquei em minimizar");
    }//GEN-LAST:event_L_minimizarMouseClicked

    private void L_maximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_maximizarMouseClicked
        System.out.println("cliquei em maximizar");
    }//GEN-LAST:event_L_maximizarMouseClicked

    private void Area_trabalhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Area_trabalhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Area_trabalhoMouseClicked
                                     

    public void ajustar_tela(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
    int largura = (int) Math.round(width);
     int altura = (int) Math.round(height);
//        L_imagem.setSize(1366,35);
//        ImageIcon icon = new ImageIcon("src/semestral/imagem/topo/imagem_topo.png");
//        icon.setImage(icon.getImage().getScaledInstance(
//        L_imagem.getWidth(), L_imagem.getHeight(),1));
//        L_imagem.setIcon(icon);
//        System.out.print(this.getSize());
       
        System.out.println("tamnho do menu "+Area_menu.getSize() + "/n");
         System.out.println("tamnho do area "+Area_trabalho.getSize()+ "/n");
    }
    public  void fechar(){
        this.dispose();
    }
//    /**
//     * @param args the command line arguments
//     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Area_menu;
    private javax.swing.JDesktopPane Area_trabalho;
    private javax.swing.JLabel L_fechar;
    private javax.swing.JLabel L_imagem;
    private javax.swing.JLabel L_maximizar;
    private javax.swing.JLabel L_minimizar;
    // End of variables declaration//GEN-END:variables
}
