/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semestral.view.avaliacao;

import semestral.view.treinos.*;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author guilh
 */
public class tela_avalicao extends javax.swing.JInternalFrame {

    /**
     * Creates new form tela_treino
     */
    public tela_avalicao(Dimension tamanho) {
        initComponents();
        this.setSize(tamanho);
        L_imagem.setSize(tamanho);
        ImageIcon icon = new ImageIcon("src/semestral/imagem/area_trabalho/Area de Trabalho Avaliação Light.png");
        icon.setImage(icon.getImage().getScaledInstance(
        L_imagem.getWidth(), L_imagem.getHeight(),1));
        L_imagem.setIcon(icon);
        System.out.print(this.getSize());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_imagem = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);
        getContentPane().add(L_imagem);
        L_imagem.setBounds(3, 0, 390, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_imagem;
    // End of variables declaration//GEN-END:variables
}
