/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semestral.view.aluno;

import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import semestral.dao.aluno.aluno_DAO;
import semestral.dao.pessoa.pessoa_DAO;
import semestral.view.navegacao;
import semestral.view.tela_home;



/**
 *
 * @author guilh
 */
public class tela_aluno extends javax.swing.JInternalFrame {
    aluno_DAO aluno_dao = new aluno_DAO();
    navegacao navega = new navegacao();
    pessoa_DAO pessoa_dao = new pessoa_DAO();
    
    /**
     * Creates new form tela_aluno
     */
   JDesktopPane area_menu;
    JDesktopPane area_trabalho;
    JInternalFrame tela;
    Dimension dimensao ; 
    int id_aluno = 0;
    public tela_aluno(Dimension tamanho,JDesktopPane area_menu_,JDesktopPane area_trabalho_, JInternalFrame aba) {
        initComponents();
        this.setSize(tamanho);
        area_menu = area_menu_;
        area_trabalho = area_trabalho_;
        tela = aba;
        dimensao = tamanho;
        L_imagem.setSize(tamanho);
//        ImageIcon icon = new ImageIcon("src/semestral/imagem/area_trabalho/Area de trabalho Light.png");;
//        icon.setImage(icon.getImage().getScaledInstance(
//        L_imagem.getWidth(), L_imagem.getHeight(),1));
//        L_imagem.setIcon(icon);
//       //pessoa_dao.buscar_pessoa_nome("");
        buscar_aluno_nome();
    }
    
    public void buscar_aluno_nome(){
        remover_linha();
    String[][] lista_pessoa = aluno_dao.buscar_aluno_tela_aluno(T_buscar_nome.getText());
       int n = lista_pessoa.length;
        System.out.println("recebi "+n+" itens");
//       int j = lista_pessoa[0].length;
       String[] id_pessoa_ = new String[n];
    
    for (int i=0; i<n; i++) {
         DefaultTableModel dtm = (DefaultTableModel)T_aluno.getModel();
         dtm.addRow(new Object[]{lista_pessoa[i][0],lista_pessoa[i][1],lista_pessoa[i][2],lista_pessoa[i][3],lista_pessoa[i][4]});
           id_pessoa_ [i]= (lista_pessoa[i][0]);    
    }
    }
   
    public void remover_linha(){
        DefaultTableModel dtm = (DefaultTableModel) T_aluno.getModel();
        
        for (int linhas = dtm.getRowCount(); linhas != 0; linhas --){
            dtm.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T_aluno = new javax.swing.JTable();
        B_cadastrar = new javax.swing.JLabel();
        L_imagem = new javax.swing.JLabel();
        T_buscar_nome = new javax.swing.JTextField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(136, 720));
        getContentPane().setLayout(null);

        T_aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Data Treino inicio", "Data Treino termino", "Data Avalição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        T_aluno.setRowHeight(25);
        T_aluno.setShowVerticalLines(false);
        T_aluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_alunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(T_aluno);
        T_aluno.getColumnModel().getColumn(0).setPreferredWidth(30);
        T_aluno.getColumnModel().getColumn(1).setPreferredWidth(600);
        T_aluno.getColumnModel().getColumn(2).setPreferredWidth(100);
        T_aluno.getColumnModel().getColumn(3).setPreferredWidth(100);
        T_aluno.getColumnModel().getColumn(4).setPreferredWidth(120);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 1240, 600);

        B_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_cadastrarMouseClicked(evt);
            }
        });
        getContentPane().add(B_cadastrar);
        B_cadastrar.setBounds(31, 26, 220, 50);

        L_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/semestral/imagem/area_trabalho/Area Alunos Lista Light.png"))); // NOI18N
        L_imagem.setPreferredSize(new java.awt.Dimension(1250, 740));
        getContentPane().add(L_imagem);
        L_imagem.setBounds(0, 0, 1206, 742);

        T_buscar_nome.setBackground(new java.awt.Color(230, 231, 232));
        T_buscar_nome.setBorder(null);
        T_buscar_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_buscar_nomeActionPerformed(evt);
            }
        });
        T_buscar_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                T_buscar_nomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_buscar_nomeKeyReleased(evt);
            }
        });
        getContentPane().add(T_buscar_nome);
        T_buscar_nome.setBounds(880, 30, 250, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_cadastrarMouseClicked
        tela_cadastro_aluno tela_ = new tela_cadastro_aluno(dimensao, area_menu, area_trabalho,tela, id_aluno);
        tela_cadastro_aluno_menu menu_= new tela_cadastro_aluno_menu(area_menu.getSize(), area_menu, area_trabalho, tela_);
        tela_ = new tela_cadastro_aluno(dimensao, area_menu, area_trabalho,menu_,id_aluno);
        navega.navegar(area_trabalho, area_menu, tela_, menu_, this, tela);

    }//GEN-LAST:event_B_cadastrarMouseClicked

    private void T_buscar_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_buscar_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_buscar_nomeActionPerformed

    private void T_buscar_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_buscar_nomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_buscar_nomeKeyPressed

    private void T_buscar_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_buscar_nomeKeyReleased
        buscar_aluno_nome();
    }//GEN-LAST:event_T_buscar_nomeKeyReleased

    private void T_alunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_alunoMouseClicked
       if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            int x = T_aluno.getSelectedRow();
            int y = T_aluno.getSelectedColumn();
            DefaultTableModel dtm = (DefaultTableModel) T_aluno.getModel();
            Object teste = dtm.getValueAt(x, y);
            JOptionPane.showMessageDialog(this, teste);
            id_aluno = Integer.parseInt(dtm.getValueAt(x, 0)+"");
            if(y == 0 || y == 1){
        tela_cadastro_aluno tela_ = new tela_cadastro_aluno(dimensao, area_menu, area_trabalho,tela, id_aluno);
        tela_cadastro_aluno_menu menu_= new tela_cadastro_aluno_menu(area_menu.getSize(), area_menu, area_trabalho, tela_);
        tela_ = new tela_cadastro_aluno(dimensao, area_menu, area_trabalho,menu_,id_aluno);
        id_aluno = 0;
        navega.navegar(area_trabalho, area_menu, tela_, menu_, this, tela);
            
            }
            
        }
        
    }//GEN-LAST:event_T_alunoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_cadastrar;
    private javax.swing.JLabel L_imagem;
    private javax.swing.JTable T_aluno;
    private javax.swing.JTextField T_buscar_nome;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
